config/routes.rb
VimWatchin::Application.routes.draw do

  resources :photos

  resources :events

  resources :pawnshops

  get "users/index"

root :to => "demo#index"

  post "demo/index"

  get "demo/index"

match 'auth/:provider/callback', to: 'sessions#create'
match 'auth/failure', to: redirect('/')
match 'signout', to: 'sessions#destroy', as: 'signout'

  match ':controller(/:action(/:id))' , :via => :get
end

app/models/pawnshop.rb
 class Pawnshop < ActiveRecord::Base
  attr_accessible :Reference_link1, :Reference_link2, :Reference_link3, :accessories, :actor_id, :avaialble_from, :avaialble_till, :category, :comment, :contact, :created, :description, :images, :model_number, :modified, :negotiable, :pageview, :pick_up_location1, :pick_up_location2, :pick_up_location3, :pick_up_location4, :pick_up_location5, :price, :product_title, :purchase_date, :reason_for_sale, :spam, :sub_cartegory, :type_pawn, :visible, :voteup, :image
   #mount_uploader :image, ImageUploader
end

app/controllers/pawnshops_controller.rb
class PawnshopsController < ApplicationController
  # GET /pawnshops
  # GET /pawnshops.json
  def index
    @pawnshops = Pawnshop.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pawnshops }
    end
  end

  # GET /pawnshops/1
  # GET /pawnshops/1.json
  def show
    @pawnshop = Pawnshop.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pawnshop }
    end
  end

  # GET /pawnshops/new
  # GET /pawnshops/new.json
  def new
    @pawnshop = Pawnshop.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pawnshop }
    end
  end

  # GET /pawnshops/1/edit
  def edit
    @pawnshop = Pawnshop.find(params[:id])
  end

  # POST /pawnshops
  # POST /pawnshops.json
  def create
    @pawnshop = Pawnshop.new(params[:pawnshop])

    respond_to do |format|
      if @pawnshop.save
        format.html { redirect_to @pawnshop, notice: 'Pawnshop was successfully created.' }
        format.json { render json: @pawnshop, status: :created, location: @pawnshop }
      else
        format.html { render action: "new" }
        format.json { render json: @pawnshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pawnshops/1
  # PUT /pawnshops/1.json
  def update
    @pawnshop = Pawnshop.find(params[:id])

    respond_to do |format|
      if @pawnshop.update_attributes(params[:pawnshop])
        format.html { redirect_to @pawnshop, notice: 'Pawnshop was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pawnshop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pawnshops/1
  # DELETE /pawnshops/1.json
  def destroy
    @pawnshop = Pawnshop.find(params[:id])
    @pawnshop.destroy

    respond_to do |format|
      format.html { redirect_to pawnshops_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/pawnshops_helper.rb
module PawnshopsHelper
end

app/views/pawnshops/_form.html.erb
<%= form_for(@pawnshop) do |f| %>
  <% if @pawnshop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pawnshop.errors.count, "error") %> prohibited this pawnshop from being saved:</h2>

      <ul>
      <% @pawnshop.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :actor_id %><br />
    <%= f.text_field :actor_id %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :sub_cartegory %><br />
    <%= f.text_field :sub_cartegory %>
  </div>
  <div class="field">
    <%= f.label :product_title %><br />
    <%= f.text_field :product_title %>
  </div>
  <div class="field">
    <%= f.label :model_number %><br />
    <%= f.text_field :model_number %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :images %><br />
    <%= f.text_field :images %>
  </div>
  <div class="field">
    <%= f.label :Reference_link1 %><br />
    <%= f.text_field :Reference_link1 %>
  </div>
  <div class="field">
    <%= f.label :Reference_link2 %><br />
    <%= f.text_field :Reference_link2 %>
  </div>
  <div class="field">
    <%= f.label :Reference_link3 %><br />
    <%= f.text_field :Reference_link3 %>
  </div>
  <div class="field">
    <%= f.label :purchase_date %><br />
    <%= f.date_select :purchase_date %>
  </div>
  <div class="field">
    <%= f.label :reason_for_sale %><br />
    <%= f.text_field :reason_for_sale %>
  </div>
  <div class="field">
    <%= f.label :accessories %><br />
    <%= f.text_field :accessories %>
  </div>
  <div class="field">
    <%= f.label :contact %><br />
    <%= f.text_field :contact %>
  </div>
  <div class="field">
    <%= f.label :pick_up_location1 %><br />
    <%= f.text_field :pick_up_location1 %>
  </div>
  <div class="field">
    <%= f.label :pick_up_location2 %><br />
    <%= f.text_field :pick_up_location2 %>
  </div>
  <div class="field">
    <%= f.label :pick_up_location3 %><br />
    <%= f.text_field :pick_up_location3 %>
  </div>
  <div class="field">
    <%= f.label :pick_up_location4 %><br />
    <%= f.text_field :pick_up_location4 %>
  </div>
  <div class="field">
    <%= f.label :pick_up_location5 %><br />
    <%= f.text_field :pick_up_location5 %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price %>
  </div>
  <div class="field">
    <%= f.label :negotiable %><br />
    <%= f.check_box :negotiable %>
  </div>
  <div class="field">
    <%= f.label :spam %><br />
    <%= f.text_field :spam %>
  </div>
  <div class="field">
    <%= f.label :visible %><br />
    <%= f.check_box :visible %>
  </div>
  <div class="field">
    <%= f.label :pageview %><br />
    <%= f.number_field :pageview %>
  </div>
  <div class="field">
    <%= f.label :voteup %><br />
    <%= f.text_field :voteup %>
  </div>
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :created %><br />
    <%= f.datetime_select :created %>
  </div>
  <div class="field">
    <%= f.label :modified %><br />
    <%= f.datetime_select :modified %>
  </div>
  <div class="field">
    <%= f.label :type_pawn %><br />
    <%= f.text_field :type_pawn %>
  </div>
  <div class="field">
    <%= f.label :avaialble_from %><br />
    <%= f.datetime_select :avaialble_from %>
  </div>
  <div class="field">
    <%= f.label :avaialble_till %><br />
    <%= f.datetime_select :avaialble_till %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pawnshops/edit.html.erb
<h1>Editing pawnshop</h1>

<%= render 'form' %>

<%= link_to 'Show', @pawnshop %> |
<%= link_to 'Back', pawnshops_path %>

app/views/pawnshops/index.html.erb
<h1>Listing pawnshops</h1>

<table>
  <tr>
    <tr>
    <th>Actor</th>
    <th>Category</th>
    <th>Sub cartegory</th>
    <th>Product title</th>
    <th>Model number</th>
    <th>Description</th>
    <th>Images</th>
    <th>Reference link1</th>
    <th>Reference link2</th>
    <th>Reference link3</th>
    <th>Purchase date</th>
    <th>Reason for sale</th>
    <th>Accessories</th>
    <th>Contact</th>
    <th>Pick up location1</th>
    <th>Pick up location2</th>
    <th>Pick up location3</th>
    <th>Pick up location4</th>
    <th>Pick up location5</th>
    <th>Price</th>
    <th>Negotiable</th>
    <th>Spam</th>
    <th>Visible</th>
    <th>Pageview</th>
    <th>Voteup</th>
    <th>Comment</th>
    <th>Created</th>
    <th>Modified</th>
    <th>Type pawn</th>
    <th>Avaialble from</th>
    <th>Avaialble till</th>
    <th></th>
    <th></th>
    <th></th>
</tr>
  </tr>

<% @pawnshops.each do |pawnshop| %>
  <tr>
    <td><%= pawnshop.actor_id %></td>
    <td><%= pawnshop.category %></td>
    <td><%= pawnshop.sub_cartegory %></td>
    <td><%= pawnshop.product_title %></td>
    <td><%= pawnshop.model_number %></td>
    <td><%= pawnshop.description %></td>
    <td><%= pawnshop.images %></td>
    <td><%= pawnshop.Reference_link1 %></td>
    <td><%= pawnshop.Reference_link2 %></td>
    <td><%= pawnshop.Reference_link3 %></td>
    <td><%= pawnshop.purchase_date %></td>
    <td><%= pawnshop.reason_for_sale %></td>
    <td><%= pawnshop.accessories %></td>
    <td><%= pawnshop.contact %></td>
    <td><%= pawnshop.pick_up_location1 %></td>
    <td><%= pawnshop.pick_up_location2 %></td>
    <td><%= pawnshop.pick_up_location3 %></td>
    <td><%= pawnshop.pick_up_location4 %></td>
    <td><%= pawnshop.pick_up_location5 %></td>
    <td><%= pawnshop.price %></td>
    <td><%= pawnshop.negotiable %></td>
    <td><%= pawnshop.spam %></td>
    <td><%= pawnshop.visible %></td>
    <td><%= pawnshop.pageview %></td>
    <td><%= pawnshop.voteup %></td>
    <td><%= pawnshop.comment %></td>
    <td><%= pawnshop.created %></td>
    <td><%= pawnshop.modified %></td>
    <td><%= pawnshop.type_pawn %></td>
    <td><%= pawnshop.avaialble_from %></td>
    <td><%= pawnshop.avaialble_till %></td>
    <td><%= link_to 'Show', pawnshop %></td>
    <td><%= link_to 'Edit', edit_pawnshop_path(pawnshop) %></td>
    <td><%= link_to 'Destroy', pawnshop, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Pawnshop', new_pawnshop_path %>

app/views/pawnshops/new.html.erb
<h1>New pawnshop</h1>
	<%=file_field :files,mutiple: true %>

<%= render 'form' %>
<%= link_to 'Back', pawnshops_path %>

</form>

app/views/pawnshops/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Actor:</b>
  <%= @pawnshop.actor_id %>
</p>

<p>
  <b>Category:</b>
  <%= @pawnshop.category %>
</p>

<p>
  <b>Sub cartegory:</b>
  <%= @pawnshop.sub_cartegory %>
</p>

<p>
  <b>Product title:</b>
  <%= @pawnshop.product_title %>
</p>

<p>
  <b>Model number:</b>
  <%= @pawnshop.model_number %>
</p>

<p>
  <b>Description:</b>
  <%= @pawnshop.description %>
</p>

<!-- <p>
  <b>Images:</b>
  <%= @pawnshop.images %>
  <%= file_field :image %>

</p> -->

<p>
  <b>Reference link1:</b>
  <%= @pawnshop.Reference_link1 %>
</p>

<p>
  <b>Reference link2:</b>
  <%= @pawnshop.Reference_link2 %>
</p>

<p>
  <b>Reference link3:</b>
  <%= @pawnshop.Reference_link3 %>
</p>

<p>
  <b>Purchase date:</b>
  <%= @pawnshop.purchase_date %>
</p>

<p>
  <b>Reason for sale:</b>
  <%= @pawnshop.reason_for_sale %>
</p>

<p>
  <b>Accessories:</b>
  <%= @pawnshop.accessories %>
</p>

<p>
  <b>Contact:</b>
  <%= @pawnshop.contact %>
</p>

<p>
  <b>Pick up location1:</b>
  <%= @pawnshop.pick_up_location1 %>
</p>

<p>
  <b>Pick up location2:</b>
  <%= @pawnshop.pick_up_location2 %>
</p>

<p>
  <b>Pick up location3:</b>
  <%= @pawnshop.pick_up_location3 %>
</p>

<p>
  <b>Pick up location4:</b>
  <%= @pawnshop.pick_up_location4 %>
</p>

<p>
  <b>Pick up location5:</b>
  <%= @pawnshop.pick_up_location5 %>
</p>

<p>
  <b>Price:</b>
  <%= @pawnshop.price %>
</p>

<p>
  <b>Negotiable:</b>
  <%= @pawnshop.negotiable %>
</p>

<p>
  <b>Spam:</b>
  <%= @pawnshop.spam %>
</p>

<p>
  <b>Visible:</b>
  <%= @pawnshop.visible %>
</p>

<p>
  <b>Pageview:</b>
  <%= @pawnshop.pageview %>
</p>

<p>
  <b>Voteup:</b>
  <%= @pawnshop.voteup %>
</p>

<p>
  <b>Comment:</b>
  <%= @pawnshop.comment %>
</p>

<p>
  <b>Created:</b>
  <%= @pawnshop.created %>
</p>

<p>
  <b>Modified:</b>
  <%= @pawnshop.modified %>
</p>

<p>
  <b>Type pawn:</b>
  <%= @pawnshop.type_pawn %>
</p>

<p>
  <b>Avaialble from:</b>
  <%= @pawnshop.avaialble_from %>
</p>

<p>
  <b>Avaialble till:</b>
  <%= @pawnshop.avaialble_till %>
</p>


<%= link_to 'Edit', edit_pawnshop_path(@pawnshop) %> |
<%= link_to 'Back', pawnshops_path %>